 ### live server test
GET http://localhost:8000

# ========================= Admin registration and login

### Admin user registration
POST http://localhost:8000/api/v1/register-login
Content-Type: application/json

{
    "fName" : "garry",
    "lName" : "amasia",
    "dob" : "1987-11-23",
    "phone" : "040598828",
    "email" : "jimmy@outlook.com",
    "password" : "123123",
    "address" : "westmead"

}
